### ISSUE TITLE
Running via Linqpad

### ISSUE THREAD

**Issue by mcintyre321** [adamralph/bullseye#201]
Hi. Just thought I'd give bullseye a very quick whirl in Linqpad and I see a couple of (cosmetic) issues:

![image](https://user-images.githubusercontent.com/275706/50218531-2dc59280-0384-11e9-90b2-3bdbf334bff2.png)

1. the display is a bit odd, I guess there's some encoding/decoding difference. Do you know what it is, and I can see if I can get Linqpad to output correctly?
2. you get a "Query ended unexpectedly" message - I can avoid this by using `RunTargets(args)` but I see that's being deprecated...

I appreciate Linqpad's not been targeted for support, but if the problems are easy to fix then it would be neat to be able to use it with bullseye.

**Comment by adamralph** [comment]
Hi @mcintyre321, thanks for raising this.

1. This is because the LINQpad output window does not support ANSI colour codes. The best I can suggest is that you raise a feature request with LINQPad (I don't know how that is done) to support ANSI colour codes. In the meantime, you can workaround it by switching off coloured output with the `-N|--no-color option`.
2. Yes, that's because `RunTargetsAndExit` calls `Environment.Exit`. The idea is that no one should need to write any code after calling `RunTargetsAndExit`. The advantage of the new method is that exceptions thrown inside targets can be logged and the process can exit cleanly with an exit code rather than an unhandled exception, which results in a useless stack trace in the console window and (on Windows at least) a multi-second delay while multiple application errors are written to the OS event log.

Before investigating item 2 further, may I ask:

- what is the use case for using LINQPad rather than a console app plus an IDE or `dotnet run`?
- does the "Query ended unexpectedly" message cause you problems?

**Comment by mcintyre321** [comment]
Looks like it's all purely cosmetic - if I run the script via the command line using `lprun.exe` then the exit code is 0 even with "Query ended unexpectedly", and the output is colourised and lovely :)

Use case is that I ❤️ Linqpad as it's so much quicker to work with than a VS project (although I should probably migrate to RoslynPad or some other csx runner as LP is commercial).

Thanks for your time!

**Comment by adamralph** [comment]
OK, great.

Out of interest, what is it that is "quicker" about working with a Linqpad (or RoslynPad or some other csx runner) than a console app? Bear in mind that you can edit a console app using VS Code, or any other IDE/smart text editor, and you can run it with `dotnet run`.

**Comment by mcintyre321** [comment]
I don't know if you've used a licence copy of Linqpad before (which makes all the difference, for intellisense, nuget and debugger), but it runs as quickly as notepad, and  seemingly compiles as fast as your F5 keypress.

The best thing though is the amazing `.Dump()` method that lets you display objects/HTML/Wpf/Winforms Controls so you can rapidly prototype tiny GUIs, or try out libraries and stuff. 

/advert :)

There are a few .Dump extensions and stuff for VSCode, but the experience just isn't as good.

**Comment by adamralph** [comment]
Fair enough. And yes, I'm using a licensed copy of Linqpad. It's great. 🙂 Although I wouldn't use it for the build script of an OSS project since it would add more pre-requisite burden on contributors. I can see that for an internal project it may be a good choice. I guess you'd also need to bootstrap it somehow for your CI build agents. That's what I really love about using a console app: no boostrapping apart from the .NET SDK, which is required anyway if building .NET projects.
