### ISSUE TITLE
BeforeTarget and AfterTarget

### ISSUE THREAD

**Issue by damianh** [adamralph/bullseye#218]
I would like to be able to run an action before and after each target run.

My particular use case is that I want to write a TC service message before and after each Task.

```csharp
BeforeTarget((targetName) => Console.WriteLine($"##teamcity[blockOpened name='{targetName}']");
```

```csharp
AfterTarget((targetName) => Console.WriteLine($"##teamcity[blockClosed name='{targetName}']");
```

Happy to attempt a PR if agreeable. My current workaround is to have my own `TargetTC` methods that wrap `Target` and it's a bit meh

```csharp
private static void TargetTC(string name, Action action)
{
    Target(name, () =>
    {
        Console.WriteLine($"##teamcity[blockOpened name='{name}']");
        action();
        Console.WriteLine($"##teamcity[blockClosed name='{name}']");
    });
}
```

**Comment by adamralph** [comment]
@damianh how about we go a step further and just write out those messages whenever running on TC? We already do ["host" detection](https://github.com/adamralph/bullseye/blob/9674055a7e415a992d73612e7488516a4877d1b4/Bullseye/Internal/ConsoleExtensions.cs#L37-L57). We could then pass the `host` to the [`Logger` constructor](https://github.com/adamralph/bullseye/blob/9674055a7e415a992d73612e7488516a4877d1b4/Bullseye/Internal/ConsoleExtensions.cs#L60) and alter `Logger` so that it writes out TC messages in addition to those it is already writing, where appropriate. I'd be happy to take a PR for that.

**Comment by damianh** [comment]
Well if you already do host detection, then 👍

**Comment by damianh** [comment]
Happy enough with a couple of `if` statements? We don't want `Logger` with some virtuals and a derived `TeamCityLogger`? :)

**Comment by adamralph** [comment]
Yeah, `if`s are fine.

**Comment by damianh** [comment]
Tried the `if`s... it looks a bit nasty maintenance wise tbh. https://github.com/damianh/bullseye/commit/cc390f15a555e80c636f0ed75fb4fd2bc7ab3f37

Can we do something better here?

**Comment by damianh** [comment]
Would doing this inside `ActionTarget.RunAsync` and `ActionTarget<TInput>.InvokeAsync` be a better place?

**Comment by adamralph** [comment]
@damianh I think the logger is the right place to do it. The change does introduce some noise, but I find it acceptable. Two observations:

- The TC message start/end messages and the regular start/end messages should probably be nested. Perhaps the TC messages should be outside the regular messages? I.e. the message order would be: TC start, regular start, regular end (success/failure), TC end.
- The TC messages for the start of a target for a particular input value should probably contain the input value, otherwise there will be several TC start/end messages with the same target name.

**Comment by adamralph** [comment]
Replaced by #248.
