### ISSUE TITLE
Provide a way to create dependency chain in isolation

### ISSUE THREAD

**Issue by Mpdreamz** [adamralph/bullseye#229]
One thing I love about FAKE is that it promotes the separation of defining targets and defining dependency chains.

e.g part of our current build that I am converting over to BullsEye

```fsharp
"Start"
    =?> ("Clean", Commandline.needsClean )
    =?> ("Version", hasBuildParam "version")
    ==> "Restore"
    =?> ("FullBuild", Commandline.needsFullBuild)
    =?> ("Test", (not Commandline.skipTests && Commandline.target <> "canary"))
    =?> ("InternalizeDependencies", (not isMono))
    ==> "InheritDoc"
    =?> ("Documentation", (not Commandline.skipDocs))
    ==> "Build"
```

`=?>` denotes a conditional target which will only run if the predicate is `true`. 

Not sure how to work this into the current DSL but I found there was a bit of cognitive overload on my end trying to rework this as arguments to the target creation.

**Comment by Mpdreamz** [comment]
`Target(name, dependencies)` suffices and returning from the tasks early. 

However makes them show up in the graph and summary making it look like they executed.

**Comment by adamralph** [comment]
Hey @Mpdreamz thanks for raising this. I'm on the road right now but I'll look into this ASAP.

**Comment by adamralph** [comment]
@Mpdreamz I think I know how this can be done. I've earmarked it for 3.0.0.

We can allow a target to be defined multiple times, with each definition adding to the last. That is, I can write:

```c#
Target("hello-world", DependsOn("foo"), () => Console.Write("Hello,"));

Target("hello-world", DependsOn("bar"), () => Console.WriteLine(" world!"));
```

When `hello-world` is executed, both `foo` and `bar` will be executed as dependencies, and both the delegates will be executed. Another build tool I wrote a few years ago supported multiple definitions, and so do some others, such as Rake. I'm not yet sure whether, in the above example, only `foo` should execute before the first delegate, and `bar` should only execute before the second delegate, but that can be thought about later, perhaps looking to Rake for precedent.

So in your use case, you could choose to only define dependencies in the second set of definitions:

```c#
Target("make-tea", () => Console.WriteLine("Tea made."));
Target("drink-tea", () => Console.WriteLine("Ahh... lovely!"));
Target("walk-dog", () => Console.WriteLine("Walkies!"));

Target("drink-tea", DependsOn("make-tea"));
Target("default", DependsOn("drink-tea", "walk-dog"));
```

I know there are other things going in the FAKE example you've given, such as conditional execution, but I'd prefer to deal with that in a separate issue, if required.

Thoughts?

**Comment by adamralph** [comment]
> 
> 
> `Target(name, dependencies)` suffices and returning from the tasks early.
> 
> However makes them show up in the graph and summary making it look like they executed.

@Mpdreamz I don't understand this comment. Please can you explain?

**Comment by adamralph** [comment]
@Mpdreamz I started to spike this, but it turns out to be a little more involved than I thought (but still, ultimately, possible). Before going further, I'd like to validate the use case a little.

I realise that defining the dependency graph in the way you describe is canonical in FAKE, but I'd like to present a counterargument:

When defining a target, the best way to determine, and validate, it's dependencies is by looking at what that target does. That is, what is contain in its `action`. Ergo, I would argue that I would want to list the dependencies right next to the `action` definition. For example:

```c#
Target("build", () => Run("dotnet", "build"));

Target("test", () => Run("dotnet", "test --no--build"));
```

Now we ask "What does the test target depend on?". Well, clearly when writing the target we assumed that the project would be built already, since we are specifying `--no-build` so we better add `"build"` as a dependency:

```c#
Target("test", DependsOn("build") => Run("dotnet", "test --no--build"));
```

And we have the opposite scenario:

```c#
Target("build", () => Run("dotnet", "build"));

Target("test", DependsOn("build") => Run("dotnet", "test --no--build"));

Target("pack", DependsOn("build", "test") => Run("dotnet", "pack --no-build"));
```

We can ask "Does pack have valid dependencies?". Well, `dotnet pack` does not need `dotnet test` to have run beforehand. It will succeed or fail regardless of whether `dotnet test` has run, so we better remove that dependency:

```c#
Target("pack", DependsOn("build") => Run("dotnet", "pack --no-build"));
```

I also realise that the canonical FAKE approach serves as a convenient way to see the dependency graph in one place. But that is what Bullseye's `--tree/-t` option is designed for:

![image](https://user-images.githubusercontent.com/677704/63577667-3283bb80-c58f-11e9-86bd-9bad3068dd10.png)

There are various benefits to this over the dependency graph in code. For example, each dependency path is followed, which gives the entire dependency tree. And this a rendering of _actual_ graph, whereas the formatting/structure of the dependency graph in code could potentially be misrepresentative. I'd also argue that it's easier to read.

Thoughts?

**Comment by adamralph** [comment]
BTW if the `action` arguments for some of the targets are big blocks of code, which spread the targets across a large file, there is always the possibility to define a DSL. This is the kind of thing that the folks over in [SQLStreamStore.Docker](https://github.com/SQLStreamStore/SQLStreamStore.Docker/blob/85efcd3bc8bc2b01a0d1a975339c7d9dddd832c4/build/Program.cs) have done.

**Comment by Mpdreamz** [comment]
Its more about being able to signal that a target elected not to run

Example from my DSL https://github.com/elastic/elasticsearch-net/blob/master/build/scripts/Targets.fs

```fsharp
conditional (parsed.Target = "canary") "nuget-pack-versioned" <| fun _ -> Release.NugetPackVersioned artifactsVersion
```

```fsharp
command "canary" [ "version"; "release"; "test-nuget-package";] <| fun _ -> printfn "Finished Release Build %O" artifactsVersion
````

```fsharp
        command "release" [ 
           "build"; "nuget-pack"; "nuget-pack-versioned"; "validate-artifacts"; "generate-release-notes"
        ] (fun _ -> printfn "Finished Release Build %O" artifactsVersion)
```

Here if I run the `canary` target it should do everything `release` does as its a dependency.

However `nuget-pack-versioned` only should not be run if the target is `canary`

This causes `nuget-pack-versioned` to always show up in the graph looking like it executed really fast.


Sorry for the terse reply, on phone in a hurry :)

**Comment by adamralph** [comment]
@Mpdreamz OK, but now we are talking about conditional target execution, rather than defining a dependency chain in isolation. Conditional target execution could be added without the ability to define a dependency chain in isolation.

Conditional target execution is something I've considered before but, so far, everytime I've considered a use case I've found it can be eliminated by reconsidering the dependency graph.

I'm an F# noob so I find your DSL difficult to read but, if I understand correctly, and if I'm guessing the purpose of each target correctly, it seems like that dependency graph could look something like this (C# equivalent):

```c#
Target("build", DependsOn("version"), ...);

Target("nuget-pack", DependsOn("build"), ...);

Target("nuget-pack-versioned", DependsOn("nuget-pack"), ...);

Target("test-nuget-package", DependsOn("nuget-pack"), ...);

Target("validate-artifacts", DependsOn("nuget-pack"), ...);

Target("generate-release-notes", ...);

Target("prepare-release", DependsOn("test-nuget-package", "validate-artifacts", "generate-release-notes"), ...);

Target("rtm", DependsOn("nuget-pack-versioned", "prepare-release"), ...);

Target("canary", DependsOn("prepare-release"), ...);
```

**Comment by adamralph** [comment]
@Mpdreamz any thoughts on the above?

**Comment by adamralph** [comment]
@Mpdreamz I'm going to close this, because I'm not convinced there is a use case for isolated dependency chains.

I'm still open to the possibility of _conditional target execution_, which is a separate feature, even if my current view is that the use case can be eliminated by restructuring the dependency graph. If you'd like to pursue that further, please raise a new issue.

**Comment by Mpdreamz** [comment]
Will do, sorry for ghosting the issue :)
