### ISSUE TITLE
[Question] specifying target when calling bullseye from script

### ISSUE THREAD

**Issue by evilpilaf** [adamralph/bullseye#256]
When using the [sample wrapper scripts](https://github.com/adamralph/bullseye#sample-wrapper-scripts) and trying to call a specific target, the call fails
```
> .\build.cmd -target Test
Unrecognized option '-t'
```

How can I pass the specific target into bullseye?

**Comment by blairconrad** [comment]
```
.\build.cmd Test
```

@adamralph, I tried to find something that demonstrated this, and it's... not actually obvious from the page.

**Comment by evilpilaf** [comment]
@blairconrad tried that but I just get `Unrecognized command or argument 'Test'`

**Comment by adamralph** [comment]
@evilpilaf are you doing something similar to this? https://gist.github.com/adamralph/d6a3167c8fe0d4e24721d8d2b9c02989

**Comment by evilpilaf** [comment]
This is how I'm doing it:
https://github.com/evilpilaf/AwsDynamoDBEasyAttributeValue/blob/bullseye/build/Build.cs

**Comment by adamralph** [comment]
OK, I know what's happening. Unfortunately, there is no way to tell the McMaster library to ignore _commands_ and add them to `RemainingArguments`. Perhaps in a future version of Bullseye we can add an explicit `--targets` option which accepts the list of targets, so that that option can fall through into `RemainingArguments` like all other options. In the meantime, you could work around this by adding your own `--targets` option, and pass the values from it through to Bullseye as raw values concatenated with `RemainingArguments`?

**Comment by evilpilaf** [comment]
Thanks @adamralph this suggestion worked perfect! Closing the issue now

**Comment by adamralph** [comment]
That's great @evilpilaf. I'll add this to this gist, which is linked from the Bullseye readme: https://gist.github.com/adamralph/d6a3167c8fe0d4e24721d8d2b9c02989
