### ISSUE TITLE
Log all output to file

### ISSUE THREAD

**Issue by LodewijkSioen** [adamralph/bullseye#631]
## Use case(s)

We would love to output a 'build.log' file. Our build is quite large and having a searchable file is quite nice.

## Description

We can capture most of the output trough `powershell "dotnet run -p Build.csproj -- %* | tee build.log"`. However some information emitted by BullsEye itself is missing. That info seems to be emitted in the standard output stream.

Possibly related to #163

## Alternatives

We tried `powershell "dotnet run -p Build.csproj -- %* 2>&1  | tee build.log"`. This isn't quite useful:
 - It messes up the colours in the console output.
 - The file contains the color control characters, making it unreadable.

## Additional context

Love this and your other libraries!

**Comment by adamralph** [comment]
Hi @LodewijkSioen, thanks for raising this.

To begin with, I'd like to explore getting this to work with existing programs such `tee`, which are designed for this job, before adding something to Bullseye.

> We can capture most of the output trough `powershell "dotnet run -p Build.csproj -- %* | tee build.log"`. However some information emitted by BullsEye itself is missing

Yes, that's because Bullseye writes its messages to standard error. Since Bullseye is a library and not an application, I didn't think it made sense for Bullseye to hijack the output stream of the calling application (e.g. a build automation console app), so the messages it emits are considered _diagnostics_ rather than output (the "output" of a library is the return value from a method call), and therefore, following the purpose of the [standard streams](https://en.wikipedia.org/wiki/Standard_streams), it writes those messages to standard error. Note that a calling application can redirect its error stream to its output stream if required. There are some exceptions to Bullseye's use of standard error: the options for help and listing targets write to standard output, because in those scenarios, Bullseye is considered to be writing output "on behalf" of the calling application. But now that I think this through a little more, I'm no longer sure that Bullseye's use of standard output and standard error is entirely logical. I may also be open to the idea of adding an optional `TextWriter` parameter for message output, which defaults to standard error, and a calling application could supply it's standard output or standard error stream as an argument.

However, I think the standard output/error aspect can be dealt with separately to this issue. If you want to sink both standard output and standard error (i.e. everything you see in the console by default) into a file, then using `2>&1` _is_ the right solution. I don't think how Bullseye uses the standard streams affects this in any way, since some of the processes you may be launching from your targets may also write some things to standard output and other things to standard error, and you don't really care — you just want to see that all in your file.

> We tried `powershell "dotnet run -p Build.csproj -- %* 2>&1 | tee build.log"`.

That is the solution I would instinctively reach for.

> It messes up the colours in the console output.

Yes, that seems to be something do with nesting the command in a `powershell` invocation. If I run the bare command (`dotnet run -p Build.csproj -- %* 2>&1 | tee build.log`) directly in PowerShell, the console output looks fine. Is that something you're able to do, instead of nesting the command?

> The file contains the color control characters, making it unreadable.

Yes, you'll have to suppress the coloured output using the `--no-color` option:

`dotnet run -p Build.csproj -- --no-color %* 2>&1 | tee build.log`

Alternatively, if you really want to preserve the coloured output in the console, you could look for some variant of `tee` which strips out the ANSI colour codes when writing to the file, or perhaps add some other command which does that for you.

> Love this and your other libraries!

Thank you for the kind words. 😊

**Comment by LodewijkSioen** [comment]
I understand the reasons why you don't want to write to the stout-stream, but the sterr-stream does't feel like the correct alternative. But hey, if Wikipedia writes that diagnostics need to go there, who am I to argue.

But thanks for nudging me towards a good solution. It's a bit cluncky, but it's one of those things you set up once and then forget about.

We now have a powershell file `build.ps1`
```
function Tee-ObjectNoColor {
    [CmdletBinding()]
    Param(
        [Parameter(Position=0, Mandatory=$true, ValueFromPipeline=$true)]
        [AllowEmptyString()]
        [string]$InputObject,

        [Parameter(Position=1, Mandatory=$true)]
        [string]$FilePath
    )

    Process {
        $InputObject -replace '\x1b\[[0-9;]*m','' | Add-Content $FilePath
        $InputObject
    }
}

Remove-Item -Path .\build.log
dotnet run -p Build.csproj -- --parallel $args 2>&1 | Tee-ObjectNoColor -FilePath build.log
```
and a  `build.bat` file with
```
@ECHO OFF
CD /D %~dp0%
powershell -command "& './BUILD.ps1' %*"
IF NOT %errorlevel%==0 PAUSE
```

We need the build.bat file so non/lesser-technical people(*) can spin up a local environment (our Continuous Deployment game isn't strong enough yet).

**Comment by adamralph** [comment]
That solution looks great! I'll close this issue now then.

> I understand the reasons why you don't want to write to the stout-stream, but the sterr-stream does't feel like the correct alternative. But hey, if Wikipedia writes that diagnostics need to go there, who am I to argue.

The fact that diagnostics go to stderr is, I believe, established. But the question remains whether Bullseye's messages are diagnostics, or are they output? I'll give that some more thought.

**Comment by adamralph** [comment]
@LodewijkSioen FYI I've raised https://github.com/adamralph/bullseye/issues/641 which is primarily about parseable output, but involves writing the current messages to standard output instead of standard error.
