### ISSUE TITLE
Better options API

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#642]
## Use case(s)

When parsing options explicitly, usually for integration with the third party command line libs, or for more advanced scenarios involving multiple target collections, the API less than ideal:

- `IOptions` and `Options` should not have `ShowHelp`. The third party command line libs provide help.
- `IOptions` and `Options` should not have `UnknownOptions`. An exception should be thrown if an option is unknown.

## Description

- Removal of `ShowHelp` and `UnknownOptions` from `IOptions` and `Options`.
- A new `CommandLine` type with `public static (IReadOnlyList<string> Targets, IOptions Options, IReadOnlyList<string> UnknownOptions, bool showHelp) Parse(IEnumerable<string> args)`

## Alternatives

Carry on using the current API. It's not ideal, but it works.

## Additional context

This is not required if [a dependency is taken on System.CommandLine](https://github.com/adamralph/bullseye/issues/558).

**Comment by alibresco** [comment]
I think some of the struggles both here and in #641 are from the fact that Bullseye mixes its engine with its interface. It’s often valuable to parse command line args or write color logs to the console, but other times it gets in the way.

A cool solution here could be to create interfaces like IOptions or ILogger that the non-static API could inject. Think of how MSBuild does its loggers, albeit in a much more domain-specific way. You could have sensible defaults while keeping things customizable for those who want it. This plays into Bullseye’s strengths as lightweight and general choice.

Modularity could also be a cleaner router to taking dependencies. A System.CommandLine integration is less risky if it’s just an interchangeable implementation, whether written by you or others. If tides change, it’s a lot less costly to switch away. You also could gain some flexibility with different release cycles or stability goals.

**Comment by adamralph** [comment]
Some interesting ideas there @alibresco but I'm not sure they change this issue or #641. Both these issues are more about making the current options and args API and the logging behaviour "make sense" rather than adding anything new. Or to put it another way, they are about making the _sensible defaults_ more sensible. Still, those defaults _could_ sit behind interface implementations, which could be interchanged, as you suggest. If you'd like to pursue those ideas further, it may be better to start one or more [discussions](https://github.com/adamralph/bullseye/discussions) or raise one or more [feature requests](https://github.com/adamralph/bullseye/issues/new/choose).

**Comment by alibresco** [comment]
Ok, I see what you're saying. What got me started thinking about this was seeing your first comment in #631 where you note that logging to standard error _is_ the approach that makes sense, at least under certain assumptions of how the library is being used. I commented here because I thought there could be more "Alternatives" than just what's listed in this issue and in #641. Because There might just not be a choice about stuff like logging or command line args that will make sense to all or even most of Bullseye's users. Instead of being forced into tough tradeoffs on these types of issues, I think there's space to avoid them entirely. The interfaces were just one idea of how to make it easier to optimize for some use cases without detracting from others.

Maybe I'm off base here and you don't think there's particularly tough tradeoffs in these two cards, just some common sense improvements. If that's the case, then yeah, I agree my comment would've fit better in a different place. I don't mean to derail.

**Comment by adamralph** [comment]
released in [4.0.0-alpha.2](https://www.nuget.org/packages/Bullseye/4.0.0-alpha.2)
