### ISSUE TITLE
Support custom command line arguments

### ISSUE THREAD

**Issue by thomaslevesque** [adamralph/bullseye#86]
Currently there's no easy way to pass custom command line arguments to a Bullseye-based program.
1. Parsing has to be done manually
2. Custom arguments have to be removed before passing the args to Bullseye

I suggest:
1. Adding a `string GetArgument(string argumentName)`, which would allow passing arguments in the form `--foo=bar`
2. Ignoring unknown arguments passed to `RunTargets` (or adding an overload with a `bool ignoreUnknownArguments` parameter)

**Comment by thomaslevesque** [comment]
> Now, if that library had a way to say "from this string array, parse out all the arguments you know about, and give the rest back to me as a string array", then we'd be in business, since that second string array could be passed straight through to Bullseye. Do any such libraries exist?

That seems unlikely, since such a feature seems overly specific. But who knows...

> I hear a lot positive noise about https://github.com/natemcmaster/CommandLineUtils these days, but I'm not familiar with it.

I used `Microsoft.Extensions.CommandLineUtils` on which it's based. It's rather nice, but I'm not sure it can easily do that. I'll check it out.

**Comment by thomaslevesque** [comment]
> That seems unlikely, since such a feature seems overly specific. But who knows...

Well, maybe I was pessimistic. https://natemcmaster.github.io/CommandLineUtils/docs/arguments.html?tabs=using-attributes#remaining-arguments
It does just what I need!

BTW, it's a bit unfortunate that you picked `-c` for "clear console", because I intended to use it for "configuration" (as in Debug/Release)... well, that ship has sailed, I guess :wink:

**Comment by adamralph** [comment]
> Well, maybe I was pessimistic. https://natemcmaster.github.io/CommandLineUtils/docs/arguments.html?tabs=using-attributes#remaining-arguments
> It does just what I need!

That's great to know!

For these scenarios, where Bullseye is kind of a "console within a console", perhaps it's worth prefixing the option names for the "outer console". For example, because the short form of Bullseye arguments will always be a single character, you could call your options something like `-xc`, and they will never clash with Bullseye options. It's worth considering, because I already have plans up my sleeve for more options, so you never know when a new version of Bullseye might start to "occupy" a specific character. 🙂

**Comment by thomaslevesque** [comment]
> For these scenarios, where Bullseye is kind of a "console within a console", perhaps it's worth prefixing the option names for the "outer console". For example, because the short form of Bullseye arguments will always be a single character, you could call your options something like -xc, and they will never clash with Bullseye options. It's worth considering, because I already have plans up my sleeve for more options, so you never know when a new version of Bullseye might start to "occupy" a specific character. 🙂

Good point. In this case, I'll stick to `-c`, because it's the usual switch for configuration in `dotnet` commands. This means `-c` won't be passed to Bullseye, but it's OK, because I don't really need the "clear console" option, and if I need it I can always use `--clear`.

**Comment by adamralph** [comment]
Fair enough, but you may want to think about what happens when someone passes `--help` (or `-h`, or `-?`), since the Bullseye help will no longer be accurate.

I guess you won't want to reproduce the entire Bullseye help less the `-c` option (you may have to update it every time you upgrade Bullseye). Perhaps one option is to print your own help first, which notes that your `-c` for configuration overrides the Bullseye `-c` for clear, and then let Bullseye print its usual help.

This is an intriguing problem space. I'll continue to think about whether there's more that Bullseye could do to support these scenarios.

One idea currently touring my mind is is to  provide an overload of `RunTargets` which accepts an `Options` type instead of `string[]`. Then the app could take full responsibility for the command line, translating its string options to Bullseye options programmatically. Obviously the app would have to provide its own help in that scenario, since Bullseye would provide none.

**Comment by thomaslevesque** [comment]
> Fair enough, but you may want to think about what happens when someone passes --help (or -h, or -?), since the Bullseye help will no longer be accurate.
> 
> I guess you won't want to reproduce the entire Bullseye help less the -c option (you may have to update it every time you upgrade Bullseye). Perhaps one option is to print your own help first, which notes that your -c for configuration overrides the Bullseye -c for clear, and then let Bullseye print its usual help.

OMG, I didn't think about that...

The reason for the whole thing is that I wanted to add a configuration switch to FakeItEasy's build command. But I'm beginning to think it's too much trouble for too little benefit...

> One idea currently touring my mind is is to provide an overload of RunTargets which accepts an Options type instead of string[]. Then the app could take full responsibility for the command line, translating its string options to Bullseye options programmatically. Obviously the app would have to provide its own help in that scenario, since Bullseye would provide none.

I was thinking about something along those lines. Sounds like a good idea. Bullseye taking care of the whole command line is convenient in most cases, but it starts to break down when you need more control.

**Comment by adamralph** [comment]
> The reason for the whole thing is that I wanted to add a configuration switch to FakeItEasy's build command.

Out of interest, what's the use case?

**Comment by thomaslevesque** [comment]
> Out of interest, what's the use case?

I'm not sure, to be honest. There have been a few times when I wanted to build in Debug mode (I don't even remember why), and I had to manually replace Release with Debug in the build script, I thought it'd be nice to have a switch.
